name: makeup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/airbrush.jpg
    - assets/images/hd.jpg
    - assets/images/matte.jpeg
    - assets/images/mineral.webp
    - assets/images/shimmwe.jpeg

